### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by FunkyGod** [aschmelyun/docker-compose-traefik#3]
```
# This docker compose file is used for developer to setup
# dev enironment quickly. Only local machine with 
# docker and docker-compose is required.
version: '3.3'
services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
    ports:
      - "8988:8989"
    volumes:
      - ./src:/service
    # tty: true
    command: /bin/sh /service/script/start.sh
    networks:
      - platform-common-net
    labels:
      - "traefik.http.services.backend-x-service.loadbalancer.server.port=8988"
      - "traefik.http.services.backend-x-service.loadbalancer.server.scheme=http"
      - traefik.http.routers.backend-x.rule=Host(`backend-x-service.localhost`)
networks:
  platform-common-net:
    external: true
```

```
version: "3"

services:
  traefik:
    image: traefik:v3.0
    restart: always
    ports:
      - 80:80
      - 8080:8080
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--entrypoints.http.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    labels:
      - "traefik.http.routers.traefik-dashboard.entrypoints=http"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.console.lab.io`)"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      - "traefik.http.routers.traefik-dashboard-api.entrypoints=http"
      - "traefik.http.routers.traefik-dashboard-api.rule=Host(`traefik.console.lab.io`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard-api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard-api.service=api@internal"

      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.routers.traefik-dashboard.middlewares=gzip@docker"
      - "traefik.http.routers.traefik-dashboard-api.middlewares=gzip@docker"

      # - "traefik.http.routers.backend-x.rule=Host(`backend-x`) && PathPrefix(`/x/`)"
      # - "traefik.http.routers.backend-auth-service.rule=PathPrefix(`/auth/`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
      interval: 3s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - platform-common-net
networks:
  platform-common-net:

    external: true
```
![image](https://github.com/aschmelyun/docker-compose-traefik/assets/39259580/3e18a516-be8b-4eba-8497-f5df353ec1ad)
![image](https://github.com/aschmelyun/docker-compose-traefik/assets/39259580/439999ee-c59a-41d1-a459-41ca889e05ed)
if I add docker port , it work well. But if use 80 port, bad gateway
